### ISSUE TITLE
(node:45154) UnhandledPromiseRejectionWarning: TypeError: this.fetch is not a function

### ISSUE THREAD

**Issue by SangVoM** [replicate/replicate-javascript#93] opened 2023-07-06 13:18 UTC
Library bug please fix it or merge https://github.com/replicate/replicate-javascript/issues/90 maybe will solve it. Thanks
```
(node:45154) UnhandledPromiseRejectionWarning: TypeError: this.fetch is not a function
    at Replicate.request (/Users/sangvo/Desktop/tool-video/node_modules/replicate/index.js:152:33)
    at Replicate.createPrediction (/Users/sangvo/Desktop/tool-video/node_modules/replicate/lib/predictions.js:26:27)
    at Replicate.run (/Users/sangvo/Desktop/tool-video/node_modules/replicate/index.js:108:47)
    at replicateImage (/Users/sangvo/Desktop/tool-video/helper/ReplicateImage.js:27:40)
    at async /Users/sangvo/Desktop/tool-video/createVideoV2.js:455:40
(Use `node --trace-warnings ...` to show where the warning was created)
(node:45154) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:45154) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by mattt** [comment] 2023-07-07 13:08
Hi @SangVoM. I'm not sure this is a duplicate of #90, because the stack trace references your local filesystem and doesn't look like it's coming from a CloudFlare worker. 

Instead, this appears to be caused by your Node.js runtime not having a `fetch` function. From the [README](https://github.com/replicate/replicate-javascript#constructor):

> On earlier versions of Node.js and other environments where global fetch isn't available, you can install a fetch function from an external package like [cross-fetch](https://www.npmjs.com/package/cross-fetch) and pass it to the fetch option in the constructor.
>
>```js
> import Replicate from "replicate";
> import fetch from "cross-fetch";
> 
> const replicate = new Replicate({
>   // get your token from https://replicate.com/account
>   auth: process.env.REPLICATE_API_TOKEN,
>   fetch: fetch,
> });
>```

**Closed** 2023-07-10 12:12 UTC
